version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
      timezone: "Europe/Amsterdam"
    groups:
      nuget:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
      timezone: "Europe/Amsterdam"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"