name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v5"

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist/brink-renovent-hru-card.js
      
      - name: Wait for GitHub to process release asset
        run: sleep 15

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"
