name: Validate

on:
  push:
    tags-ignore:
      - '**'
  pull_request:
  schedule:
    - cron: "0 10 * * 6"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
        
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"
